name            = "employeesystem"
main            = "worker.js"
compatibility_date = "2024-01-01"
account_id      = "34c05cf0fc5baa8d8121d292544c729d"

[[d1_databases]]
binding  = "DB"
database_name = "ems-database"
database_id   = "a9b03f8a-4e0b-417a-9ef1-41cf30fd03ae"

[[kv_namespaces]]
binding = "KV"
id      = "b91b4e2738264f259a0106af4dcea875"

[vars]
ENVIRONMENT = "production"

[env.production]
name = "ems-edge-api-production"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "ems-edge-api-staging"
vars = { ENVIRONMENT = "staging" }
